logstashConfig:
  logstash.yml: |
    http.host: 0.0.0.0
    xpack.monitoring.enabled: false

logstashPipeline:
  beats.conf: |
    input { beats { port => 5045 } }
    output { elasticsearch { hosts => ["http://elasticsearch-master:9200"] index => "logstash" } }

service:
  annotations: {}
  type: ClusterIP
  ports:
    - name: beats
      port: 5045
      protocol: TCP
      targetPort: 5045
